version: '3.8'
 
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    # pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
 
  # ollama-webui:
  #   build:
  #     context: .
  #     args:
  #       OLLAMA_API_BASE_URL: '/ollama/api'
  #     dockerfile: Dockerfile
  #   image: ghcr.io/ollama-webui/ollama-webui:main
  #   volumes:
  #     - ollama-webui:/app/backend/data
  #   depends_on:
  #     - ollama
  #   ports:
  #     - ${OLLAMA_WEBUI_PORT-3000}:8080
  #   environment:
  #     - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
  #     - 'WEBUI_SECRET_KEY='
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   restart: unless-stopped
  #   network_mode: "host"
  
  # test:
  #   image: nvidia/cuda:12.3.1-base-ubuntu20.04
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  
 
volumes:
  ollama: {}
  ollama-webui: {}